# Generated by Django 2.2.4 on 2020-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contagios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_region', models.IntegerField()),
                ('total_fall', models.IntegerField()),
                ('nuev_cont', models.IntegerField()),
                ('nuev_fall', models.IntegerField()),
            ],
        ),
    ]
