# Generated by Django 2.2.4 on 2020-06-24 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_acumuladonacional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acumuladonacional',
            old_name='cont',
            new_name='contagiados',
        ),
        migrations.RenameField(
            model_name='acumuladonacional',
            old_name='fall',
            new_name='fallecidos',
        ),
    ]
