# Generated by Django 2.2.4 on 2020-06-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200625_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dat_regiones',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
