# Generated by Django 2.2.4 on 2020-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_dat_regiones_nuevos_fallecidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat_regiones',
            name='examen_pcr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
